name: npm 发布

on:
  # 每当 push tag 时触发npm发布
  push:
    tags: [v*]
  # 手动触发部署
  workflow_dispatch:

jobs:
  npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
        
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # 安装依赖
      - name: Install Dependencies
        run: pnpm install

      # 运行打包脚本
      - name: Build VuePress site
        run: | 
            npm run build
            build:types

      # 执行部署
      - name: 发布到 NPM
        uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://registry.npmjs.org/  # 设置发包npm地址仓库
        - run: npm run npublish # 执行发布
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # 刚刚设置的 NPM_TOKEN
